//final List<Map<String, dynamic>>
import 'chat_Model.dart';

var jsondata1 = [
  {
    "sender": "user1",
    "message":
        "Hello Hello Hello Hello Hello Hello Hello Hello Hello Hello Hello Hello Hello Hello Hello Hello ",
    "messageType": "Text",
    "date": "12:12PM",
    "preMsg": "",
    "preMsgType": "",
    "text": "",
  },
  {
    "sender": "user2",
    "message":
        "how r u? how r u? how r u? how r u? how r u? how r u? how r u? how r u? how r u? how r u? how r u? ",
    "messageType": "Text",
    "date": "12:12PM",
    "preMsg": "",
    "preMsgType": "",
    "text": "",
  },
  {
    "sender": "user1",
    "message": "Hi",
    "messageType": "Text",
    "date": "12:12PM",
    "preMsg": "",
    "preMsgType": "",
    "text": "",
  },
  {
    "sender": "user2",
    "message": "https://youtu.be/RLzC55ai0eo?si=VFDXG330V1wejWaf",
    "messageType": "Text",
    "date": "12:12PM",
    "preMsg": "",
    "preMsgType": "",
    "text": "",
  },
  {
    "sender": "user2",
    "message": "Ok",
    "messageType": "Text",
    "date": "12:12PM",
    "preMsg": "",
    "preMsgType": "",
    "text": "",
  },
  {
    "sender": "user1",
    "message": "Hello",
    "messageType": "Text",
    "date": "12:12PM",
    "preMsg": "",
    "preMsgType": "",
    "text": "",
  },
  {
    "sender": "user2",
    "message": "how r u?",
    "messageType": "Text",
    "date": "12:12PM",
    "preMsg": "",
    "preMsgType": "",
    "text": "",
  },
  {
    "sender": "user1",
    "message": "Hi",
    "messageType": "Text",
    "date": "12:12PM",
    "preMsg": "",
    "preMsgType": "",
    "text": "",
  },
  {
    "sender": "user2",
    "message": "m fine.",
    "messageType": "Text",
    "date": "12:12PM",
    "preMsg": "",
    "preMsgType": "",
    "text": "",
  },
  {
    "sender": "user2",
    "message": "Ok",
    "messageType": "Text",
    "date": "12:12PM",
    "preMsg": "",
    "preMsgType": "",
    "text": "",
  },
  {
    "sender": "user2",
    "message": "m fine.",
    "messageType": "Text",
    "date": "12:12PM",
    "preMsg": "",
    "preMsgType": "",
    "text": "",
  },
  {
    "sender": "user2",
    "message": "Ok",
    "messageType": "Text",
    "date": "12:12PM",
    "preMsg": "",
    "preMsgType": "",
    "text": "",
  },
  {
    "sender": "user2",
    "message": "m fine.",
    "messageType": "Text",
    "date": "12:12PM",
    "preMsg": "",
    "preMsgType": "",
    "text": "",
  },
  {
    "sender": "user2",
    "message": "Ok",
    "messageType": "Text",
    "date": "12:12PM",
    "preMsg": "",
    "preMsgType": "",
    "text": "",
  },
];
var jsondata2 = [
  ChatMessage(
    sender: "user1",
    message:
        "Hello Hello Hello Hello Hello Hello Hello Hello Hello Hello Hello Hello Hello Hello Hello Hello ",
    messageType: "Text",
    date: "12:12PM",
    preMsg: "",
    preMsgType: "",
    text: "",
  ),
  ChatMessage(
    sender: "user2",
    message:
        "how r u? how r u? how r u? how r u? how r u? how r u? how r u? how r u? how r u? how r u? how r u? ",
    messageType: "Text",
    date: "12:12PM",
    preMsg: "",
    preMsgType: "",
    text: "",
  )
];
